TOPDIR = ../../..

include $(TOPDIR)/Preamble.make

DIST_FILES = i686-linux-2.6.config ia64-linux-2.6.config linux-2.6.tar.gz x86_64-linux-2.6.config

WORKFILES = i686-linux-2.6.config ia64-linux-2.6.config linux-2.6.tar.gz x86_64-linux-2.6.config

include $(TOPDIR)/Postamble.make

