TOPDIR = ..

include $(TOPDIR)/Preamble.make

SUBDIRS =			\
	extendo			\
	lock_grab		\
	logwriter		\
	lvb_torture		\
	ttest			\
	write_append_truncate	\
	write_torture

include $(TOPDIR)/Postamble.make
