TOPDIR = ../..

include $(TOPDIR)/Preamble.make

DIST_FILES = buildkernel.py run_buildkernel.py test_netfail.py ocfs2_nicdown.py

BIN_EXTRA = buildkernel.py run_buildkernel.py test_netfail.py ocfs2_nicdown.py

include $(TOPDIR)/Postamble.make


