TOPDIR = ../../..

include $(TOPDIR)/Preamble.make

DATADIR = fsck-test/small-disk

DIST_FILES = 				\
		fsck.ocfs2.00.stdout  	\
		fsck.ocfs2.01.stdout  	\
		fsck.ocfs2.02.stdout  	\
		fsck.ocfs2.03.stdout  	\
		fsck.ocfs2.04.stdout  	\
		fsck.ocfs2.05.stdout  	\
		fsck.ocfs2.06.stdout  	\
		fsck.ocfs2.07.stdout	\
		fsck.ocfs2.08.stdout  	\
		fsck.ocfs2.09.stdout	\
		fsck.ocfs2.10.stdout  	\
		fsck.ocfs2.11.stdout	\
		fsck.ocfs2.12.stdout  	\
		fsck.ocfs2.13.stdout	\
		fsck.ocfs2.14.stdout  	\
		fsck.ocfs2.15.stdout	\
		fsck.ocfs2.16.stdout  	\
		fsck.ocfs2.17.stdout	\
		fsck.ocfs2.18.stdout  	\
		fsck.ocfs2.19.stdout  	\
		fsck.ocfs2.20.stdout	\
		fsck.ocfs2.21.stdout  	\
		fsck.ocfs2.22.stdout  	\
		fsck.ocfs2.23.stdout	\
		fsck.ocfs2.24.stdout  	\
		fsck.ocfs2.25.stdout  	\
		fsck.ocfs2.26.stdout	\
		fsck.ocfs2.27.stdout  	\
		fsck.ocfs2.28.stdout  	\
		fsck.ocfs2.29.stdout	\
		fsck.ocfs2.30.stdout  	\
		fsck.ocfs2.31.stdout  	\
		fsck.ocfs2.32.stdout	\
		fsck.ocfs2.33.stdout  	\
		fsck.ocfs2.34.stdout  	\
		fsck.ocfs2.35.stdout	\
		fsck.ocfs2.36.stdout  	\
		fsck.ocfs2.37.stdout  	\
		fsck.ocfs2.38.stdout	\
		fsck.ocfs2.39.stdout  	\
		fsck.ocfs2.40.stdout  	\
		fsck.ocfs2.41.stdout	\
		fsck.ocfs2.42.stdout  	\
		fsck.ocfs2.43.stdout  	\
		fsck.ocfs2.clean.stdout

DATAFILES = 				\
		fsck.ocfs2.00.stdout  	\
		fsck.ocfs2.01.stdout  	\
		fsck.ocfs2.02.stdout  	\
		fsck.ocfs2.03.stdout  	\
		fsck.ocfs2.04.stdout  	\
		fsck.ocfs2.05.stdout  	\
		fsck.ocfs2.06.stdout  	\
		fsck.ocfs2.07.stdout	\
		fsck.ocfs2.08.stdout  	\
		fsck.ocfs2.09.stdout	\
		fsck.ocfs2.10.stdout  	\
		fsck.ocfs2.11.stdout	\
		fsck.ocfs2.12.stdout  	\
		fsck.ocfs2.13.stdout	\
		fsck.ocfs2.14.stdout  	\
		fsck.ocfs2.15.stdout	\
		fsck.ocfs2.16.stdout  	\
		fsck.ocfs2.17.stdout	\
		fsck.ocfs2.18.stdout  	\
		fsck.ocfs2.19.stdout  	\
		fsck.ocfs2.20.stdout	\
		fsck.ocfs2.21.stdout  	\
		fsck.ocfs2.22.stdout  	\
		fsck.ocfs2.23.stdout	\
		fsck.ocfs2.24.stdout  	\
		fsck.ocfs2.25.stdout  	\
		fsck.ocfs2.26.stdout	\
		fsck.ocfs2.27.stdout  	\
		fsck.ocfs2.28.stdout  	\
		fsck.ocfs2.29.stdout	\
		fsck.ocfs2.30.stdout  	\
		fsck.ocfs2.31.stdout  	\
		fsck.ocfs2.32.stdout	\
		fsck.ocfs2.33.stdout  	\
		fsck.ocfs2.34.stdout  	\
		fsck.ocfs2.35.stdout	\
		fsck.ocfs2.36.stdout  	\
		fsck.ocfs2.37.stdout  	\
		fsck.ocfs2.38.stdout	\
		fsck.ocfs2.39.stdout  	\
		fsck.ocfs2.40.stdout  	\
		fsck.ocfs2.41.stdout	\
		fsck.ocfs2.42.stdout  	\
		fsck.ocfs2.43.stdout  	\
		fsck.ocfs2.clean.stdout

include $(TOPDIR)/Postamble.make

