TOPDIR = ../..

include $(TOPDIR)/Preamble.make

DIST_FILES = parallel_cp_a 			\
	     parallel_cross_rm 			\
	     parallel_init parallel_install 	\
	     parallel_make 			\
	     parallel_make_and_cross_rm 	\
	     parallel_make_and_rm 		\
	     parallel_make_defconfig 		\
	     parallel_mkfs_and_mount 		\
	     parallel_mkfs_and_mount_domain 	\
	     parallel_tar 			\
	     parallel_tar_and_cross_rm 		\
	     parallel_tar_and_rm 		\
	     parallel_tar_domain 		\
	     parallel_tar_socket 		\
	     parallel_umount

include $(TOPDIR)/Postamble.make
