TOPDIR = ../..

include $(TOPDIR)/Preamble.make

DIST_FILES = crfiles.py dirindex.sh dirindex_background.sh dirindex_count.sh dirindex_ls.sh dirindex_rm.sh dirindexrun.sh

include $(TOPDIR)/Postamble.make

