TOPDIR = ../..

include $(TOPDIR)/Preamble.make

DIST_FILES = crdel_del_files.py crdel_gen_files.py cross_delete.py 

BIN_EXTRA = crdel_del_files.py crdel_gen_files.py cross_delete.py 

include $(TOPDIR)/Postamble.make
