TOPDIR = ../..

include $(TOPDIR)/Preamble.make

DIST_FILES = dir_create.sh file_concat.sh file_create.sh file_link.sh file_list.sh file_rename.sh file_rm.sh file_symlink.sh racer.sh
BIN_EXTRA = dir_create.sh file_concat.sh file_create.sh file_link.sh file_list.sh file_rename.sh file_rm.sh file_symlink.sh racer.sh

include $(TOPDIR)/Postamble.make
