TOPDIR = ..

include $(TOPDIR)/Preamble.make

SUBDIRS =			\
	aio-stress		\
	aio_direct		\
	basic-dual-data		\
	bonnie			\
	create_and_open		\
	create_files		\
	create_racer		\
	cross_delete		\
	db_resize		\
	dbench			\
	dirop_fileop_racer	\
	exorcist		\
	extend_and_write	\
	extend_files		\
	extendo			\
	fsx			\
	iozone			\
	kernel_build_parallel_find			\
	lock_grab		\
	logwriter		\
	lvb_torture		\
	mmap_test		\
	multi_node_mmap		\
	parallel_timing		\
	quick_appending_writes	\
	sendfiletest		\
	truncate		\
	ttest			\
	untar_files		\
	write_append_truncate	\
	write_torture

include $(TOPDIR)/Postamble.make
