TOPDIR = ..

include $(TOPDIR)/Preamble.make

SUBDIRS =			\
	aio-stress		\
	aio_direct		\
	backup_super		\
	basic-dual-data		\
	bonnie			\
	buildkernel		\
	check_file_size_limits	\
	create_and_open		\
	create_files		\
	create_racer		\
	cross_delete		\
	db_resize		\
	dbench			\
	dirop_fileop_racer	\
	dlmstress1		\
	exorcist		\
	extend_and_write	\
	extend_files		\
	extendo			\
	fill_verify_holes	\
	fsck-tests		\
	fsx			\
	inline-data		\
	iozone			\
	kernel_build_parallel_find			\
	lock_grab		\
	logwriter		\
	lvb_torture		\
	mkfs-tests		\
	mmap_test		\
	mmap_truncate		\
	multi_node_mmap		\
	open_delete		\
	parallel_timing		\
	python_common		\
	quick_appending_writes	\
	resize_test		\
	reserve_space		\
	sendfiletest		\
	splice			\
	truncate		\
	ttest			\
	tunefs-test			\
	untar_files		\
	write_append_truncate	\
	write_torture

include $(TOPDIR)/Postamble.make
